### PR TITLE
Fix german stringtable entry

### PR DESCRIPTION
**Pull request by shukari**

### CODE REVIEW

**Comment by CreepPork** [comment]
@shukari Travis CI hanged up because there is no .travis.yml file available. You need to update your branch before I can merge it.

**Comment by shukari** [comment]
@CreepPork this is because there is no travis file in your master branch... its very uncommon that the main working branch is not the master branch... i will close this pr and make a new to the (1.0.0) branch.

**Comment by CreepPork** [comment]
We have it as the current tracking release, dunno why Kex picked it, but that's how it is.

**Comment by CreepPork** [comment]
Marked as duplicate of #195.

**Pull request closed without merging**
